nodeLinker: node-modules

plugins:
  - checksum: 4cb9601cfc0c71e5b0ffd0a85b78e37430b62257040714c2558298ce1fc058f4e918903f0d1747a4fef3f58e15722c35bd76d27492d9d08aa5b04e235bf43b22
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: 'https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles/%40yarnpkg/plugin-catalogs.js'

catalogs:
  list:
    'cross-env': '5.0.5'
    next:
      'cross-env': '7.0.3'
